export var surnamesData_EN = [
    "Lunda", "Lundak", "Lundiak", "Łundyak", "Łundziak",
    "Babij", "Babiy", "Babijczuk", "Babeyczuk",
    "Jurczylo", "Jurchilo",
    "Wasylyk", "Wasylik", "Wasylikow",
    "Basiuga", "Basiuha",
    "Kislak", "Kysliak",
    "Mykytiuk", "Myketiuk", "Mykietiuk", "Mykytyn", "Mykityn",
    "Szybisty", "Szybicki",
    "Stefurak", "Sztefurak", "Stephurak",
    "Czyzowski", "Czyżowski", "Czyżewski",
    "Narozniak", "Narożniak",
    "Polowko", "Połowko", "Polofko", "Polufka",
    "Szewszuk", "Shewchuk",
    "Solomon", "Sołomon",
    "Demydiuk", "Dymydiuk",
    "Mykłyn", "Myklin",
    "Fedorak",
    "Wołczuk", "Wowczuk", "Wowchuk", "Wałczuk",
    "Skrypnyk", "Skrypka"
];

export var surnamesData_UA = [
    "Люнда", "Лунда", "Лундяк", "Люндяк", "Лундак", "Люндак",
    "Бабій", "Бабійчук", "Бабейчук",
    "Юрчило",
    "Басюґа", "Басюга",
    "Василик", "Василиков",
    "Кисляк", "Кісляк",
    "Микитюк", "Mикєтюк",
    "Шибістий", "Стефурак", "Стефурєк", "Штефорік",
    "Чижовскі", "Чижевскі",
    "Нарозняк", "Нарожняк",
    "Половко",
    "Шевчук",
    "Соломон",
    "Демидюк", "Димидюк",
    "Миклин",
    "Федорак",
    "Вовчук", "Вальчук",
    "Скрипник", "Скрипка"
];
